# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: TERCEN_VERSION
        run: |
          echo "TERCEN_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: SEMVER TERCEN_VERSION
        run: |
          SEMVER=( ${TERCEN_VERSION//./ } )
          echo "TERCEN_MAJOR=${SEMVER[0]}" >> $GITHUB_ENV
          echo "TERCEN_MINOR=${SEMVER[1]}" >> $GITHUB_ENV
          echo "TERCEN_PATCH=${SEMVER[2]}" >> $GITHUB_ENV
      - name: COMMIT_NUMBER
        run: |
          echo "COMMIT_NUMBER=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: docker login
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: docker build
        run: docker build -t tercen/pg_prediction .
      - name: docker tag/push COMMIT_NUMBER
        run: |
          docker tag tercen/pg_prediction tercen/pg_prediction:${COMMIT_NUMBER}
          docker push tercen/pg_prediction:${COMMIT_NUMBER}
      - name: docker tag/push latest
        run: |
          docker tag tercen/pg_prediction tercen/pg_prediction:latest
          docker push tercen/pg_prediction:latest
        if: env.TERCEN_VERSION == 'main'
      - name: docker minor tag version
        run: |
          docker tag tercen/pg_prediction tercen/pg_prediction:${TERCEN_MAJOR}
          docker push tercen/pg_prediction:${TERCEN_MAJOR}
          docker tag tercen/pg_prediction tercen/pg_prediction:${TERCEN_MAJOR}.${TERCEN_MINOR}
          docker push tercen/pg_prediction:${TERCEN_MAJOR}.${TERCEN_MINOR}
          docker tag tercen/pg_prediction tercen/pg_prediction:${TERCEN_MAJOR}.${TERCEN_MINOR}.${TERCEN_PATCH}
          docker push tercen/pg_prediction:${TERCEN_MAJOR}.${TERCEN_MINOR}.${TERCEN_PATCH}
        if: env.TERCEN_PATCH != ''
